version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db-servicos
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - servicos-network

volumes:
  data:

networks:
  servicos-network:
    driver: bridge
