version: "3.8"

services:
  postgres-produtos:
    image: postgres:15
    container_name: postgres-produtos
    environment:
      POSTGRES_DB: icomprasprodutos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - produtos-data:/var/lib/postgresql/data
    networks:
      - icompras-network

  postgres-clientes:
    image: postgres:15
    container_name: postgres-clientes
    environment:
      POSTGRES_DB: icomprasclientes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - clientes-data:/var/lib/postgresql/data
    networks:
      - icompras-network

  postgres-pedidos:
    image: postgres:15
    container_name: postgres-pedidos
    environment:
      POSTGRES_DB: icompraspedidos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - pedidos-data:/var/lib/postgresql/data
    networks:
      - icompras-network

volumes:
  produtos-data:
  clientes-data:
  pedidos-data:

networks:
  icompras-network:
    driver: bridge
